version: "3.9"

services:
  app:
    image: node:18
    container_name: express-app
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3076:3000"
    depends_on:
      - prisma
      - mysql-db
    command: sh -c "npm install && npm run dev"

  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma
    restart: unless-stopped
    ports:
      - "4466:4466"
    depends_on:
      - mysql-db
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql-db
            port: 3306
            user: root
            password: prisma

  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
